# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29409f2dd0bfa952884f9ce234247a11334d9c03801be05f61e9215f39c3dd7e4d8100a81be8a61204cfc549b3e869374cc5b337ea26ff867213ef6aec20f690
  facebook_app_id: "452285848297519"
  facebook_app_secret: "cd22bdc8149f956fa54b929b16e826d4"
  google_client_id: "672588688776-0eslkcbakjmve314u8pm7sj8u3eu4dmp.apps.googleusercontent.com"
  google_client_secret: "zocNkfzcCJvY1IAfLT5BRKsN"

test:
  secret_key_base: 57cdc60a0ca94c0fcc52426d501050a891ebd4a9a38e2283e50ba927c4f84ef2fea1d1b6738fb718aee74e8e0571c03649e568c96fcc286e5154e471b106dcc4
  facebook_app_id: "452285848297519"
  facebook_app_secret: "cd22bdc8149f956fa54b929b16e826d4"
  google_client_id: "672588688776-0eslkcbakjmve314u8pm7sj8u3eu4dmp.apps.googleusercontent.com"
  google_client_secret: "zocNkfzcCJvY1IAfLT5BRKsN"

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
